### PR TITLE
refs #803. Adds support for moving collections.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
Steps for testing:

1. Create a collection and perform a harvest.
2. Note the location of the collection set in /sfm-data/collection_set.
3. Create an additional collection set that is owned by a different group.
4. As admin, change the collection's collection set.
5. Verify that the location of the collection set files has changed.
6. As a member of the other group, verify that credential is available when editing the collection.

On further thought, probably a good idea to verify that collection set portability still works as expected.

**Comment by Tanych** [comment]
@justinlittman  I tested within three different situations. 
### Test  case 1
Moving when the harvester of the collection is **successful**.
* build two groups: `victor1` and `victor2`.
* add `credential_1` for `victor1`.
* create a collection_set `collection_set_1` belongs to `victor1`.
* create a collection_set `collection_set_2` belongs to `victor2`.
* create a collection `collection_1` belongs to `victor1`
* run harvester and wait for success
* move `collection_1`  to group `victor2` with the admin interface.
#### Results
The collection includes seeds, harvesters and changes log belongs to it.
**R: read,  W: write,  X: execute the collection based on the credential**

|            | victor1   | victor2    |
|------------|-----------|------------|
| collection_1 directory |           |  Owner,R,W |
| collection_1 |           |  Owner,R,W |
| credential_1 | Owner,R,W | X          |

The owner of the credential **won't change**, the new group can run the new collection with the credential but can't view and edit the credential.

### Test  case 2
Moving when  the harvester of the collection is  **running**.
* build two groups: `victor1` and `victor2`.
* add `credential_1` for `victor1`.
* create a collection_set `collection_set_1` belongs to `victor1`.
* create a collection_set `collection_set_2` belongs to `victor2`.
* create a collection (twitter filter) `collection_1` belongs to `victor1`
* run haverster and moving while the harvester is still running.
* move `collection_1`  to group `victor2` with the Admin interface.
#### Results

|            | victor1   | victor2    |
|------------|-----------|------------|
| collection_1 directory |   UNKNOWN        |  UNKNOWN |
| collection_1 |           |  Owner ,R,W |

* **The collection directory (/sfm-data/collection_set/<collection_1_Id>) disappears, neither in the source directory or destination directory.**
* The sfm-ui shows it has been moved to the `collection_set_2` and the status is running.
* Can't run the harvester as expected.

When the harvester is running, moving goes wrong. This operation needs to forbidden or documented. 

### Test  case 3
Moving with exports
* build two groups: `victor1` and `victor2`.
* add `credential_1` for `victor1`.
* create a collection_set `collection_set_1` belongs to `victor1`.
* create a collection_set `collection_set_2` belongs to `victor2`.
* create a collection `collection_1` belongs to `victor1`.
* run haverster and wait for success.
* export `collection_1` as `export_1`.
* move `collection_1`  to group `victor2` with the Admin interface.

#### Results

|            | victor1   | victor2    |
|------------|-----------|------------|
| collection_1 directory |           |  Owner,R,W |
| collection_1 |           |  Owner,R,W |
| credential_1 | Owner,R,W | X          |
| export_1 |   |  Owner        |

Source group can't view the export again but it has records on the export page. The destination group can view the export detail when type the URL but no record on the export page.

**Comment by justinlittman** [comment]
Will handle both of these cases with documentation.

**Comment by justinlittman** [comment]
@Tanych  Let me know when this is good to go.

**Comment by Tanych** [comment]
@justinlittman whether needs to add a warning info on the edit place since it might cause lose data if moving on running. If not, it's good to go.

**Pull request merged**
