### PR TITLE
Fixes #1009; adds configurable cookie consent popup

### LINKED ISSUE #1009: Cookie consent popup
Related to #1003 but keeping these issues atomic.

### PR DESCRIPTION
**Pull request by kerchner**
To test:

- Set `sfm-docker` to branch https://github.com/gwu-libraries/sfm-docker/tree/t1009-cookie-consent-envvars (in PR https://github.com/gwu-libraries/sfm-docker/pull/26 )
- Change `SFM_ENABLE_COOKIE_CONSENT` to `True` in `.env` file.
- Customize `SFM_COOKIE_CONSENT_HTML` and `SFM_COOKIE_CONSENT_BUTTON_TEXT`.  Suggested values for GW:
```
SFM_ENABLE_COOKIE_CONSENT=True
SFM_COOKIE_CONSENT_HTML=GW uses cookies and other technology on our websites to improve your website experience and to better understand how you use our websites. Visit GW's <a href="https://www.gwu.edu/privacy-notice" target="_blank" aria-label="Website privacy notice, opens in new window">Website Privacy Notice</a> to learn more about how GW uses cookies and, if you should choose, how to disable them. I understand that by clicking "I consent" and continuing to use this website, I agree to GW's use of cookies.
SFM_COOKIE_CONSENT_BUTTON_TEXT=I consent
```
- View the application and verify that the popup appears.  Click "I Consent".
- Verify that upon viewing the application again in the same browser, the popup does not appear.
- Change `SFM_ENABLE_COOKIE_CONSENT` to `False` in `.env` file.
- Open application in an incognito window - or clear cookies.
- Stop and restart the UI docker container
- Verify that the cookie consent popup does not appear.
- Build the documentation and verify the changes to the `Installation and Configuration` page

### CODE REVIEW

**Comment by kerchner** [comment]
Please do not merge when review is complete.  Instead, please @ notify me and I will squash/merge.

**Comment by lwrubel** [comment]
The cookie consent pop-up is working as expected, with default and GW text. Documentation looks good, too. A few formatting suggestions: 

- I notice that the text is centered, whereas on other GW sites it's aligned left (see the library site). If you remove the "text-center" class on the alert div in base.html, I think that should do the trick. 
- That leaves the default text hanging over too far on the left, however, so you could use the "container" class rather than "container-fluid". That also looks more in line with other GW sites, which have a similar left margin on the bar text as they do in the rest of the page.  
- While you're in there, there's a typo in the word escaping, in the comment about the safe filter.

**Comment by kerchner** [comment]
@lwrubel Left-aligned as per your recommendation

**Comment by lwrubel** [comment]
Looks good to me, @kerchner. OK to squash and merge here and in sfm-docker.

**Comment by kerchner** [comment]
@lwrubel I've also added text regarding this change to the draft release notes google doc.

**Pull request merged**
