### PR TITLE
Ref #736 add weibo advanced api doc

### PR DESCRIPTION
**Pull request by Tanych**
Ref https://github.com/gwu-libraries/sfm-ui/issues/630
Ref https://github.com/gwu-libraries/sfm-ui/issues/379
Ref https://github.com/gwu-libraries/sfm-ui/issues/724
add doc for weibo advanced API, but it needs some wording work.

### CODE REVIEW

**Comment by kerchner** [comment]
@Tanych It looks like you added an article to the project site, but I think the idea here was to update the readthedocs documentation instead.

**Comment by Tanych** [comment]
@kerchner will do.

**Comment by kerchner** [comment]
@Tanych or @lwrubel What's an easy way to test/view a branch of the github pages site?

**Comment by Tanych** [comment]
@kerchner 
using jekyll to test. You can do the following steps:

### 1. Check whether you have install `ruby`.
```
ruby --version
```
if not, install ruby first.

### 2. Install Bundler
```
gem install bundler
```
### 3.Install Jekyll and other dependencies
```
bundle install
```

### 4.Run server
```
sudo bundle exec jekyll serve
```
the default is http://localhost:4000, you can specify the host with `--host` and port with `--port`.

**Comment by kerchner** [comment]
Now connected to #736

**Comment by kerchner** [comment]
Currently running on http://gwdev-ychtan.wrlc.org:8082/

**Comment by kerchner** [comment]
Requires #807 to complete

**Comment by kerchner** [comment]
@Tanych please take a look at the updates I made and verify that I didn't change the meaning or add anything incorrect.  Thanks!

**Comment by Tanych** [comment]
@kerchner it's good to go!

**Pull request merged**
