### PR TITLE
T159 toggle active

### PR DESCRIPTION
**Pull request by justinlittman**
Fixes for #159, #181, #129.

### CODE REVIEW

**Comment by justinlittman** [comment]
Here's some items to consider testing:
* Make sure that start data has disappeared.
* Create a seed set that can have multiple seeds (e.g., twitter user timeline). Verify that seed set cannot be started until at least one seed is added.  Verify that seed set or seeds can only be edited when harvesting is paused.
* Create a seed set that can only have a single seed (e.g., twitter search). Verify that seed set cannot be started until there is a seed.  Verify that more than one seed cannot be added.
* Create a seed set that can have no seeds (e.g., weibo). Verify that a seed cannot be added and that seed set can only be edited when harvesting is paused.
* Create a stream seedset (e.g., twitter sample). Verify that a harvest start message is sent when harvesting is started (well, after waiting 15 seconds). Verify that a harvest stop message is sent when harvesting is stopped.  Verify that a harvest stop message is sent when harvest end date has passed.

**Comment by kerchner** [comment]
@justinlittman upon turning my attention back to this PR, I see that it now needs rebasing.

**Comment by kerchner** [comment]
@justinlittman I verified the items above, and also like how the SeedSet is not editable while harvesting is active.

However, I was able to add 2 seeds to a Twitter Search seedset, which should only accommodate a single seed (`Verify that more than one seed cannot be added`)

**Comment by kerchner** [comment]
It looks like perhaps you meant to add `TWITTER_SEARCH` to `SeedSet.REQUIRED_SEED_COUNTS` ?

**Comment by justinlittman** [comment]
I did and caught that later on.  It is fixed in
https://github.com/gwu-libraries/sfm-ui/commit/c353f987a2a59f5c840a748decd4986e7f083d99,
which is in a different PR.

**Comment by justinlittman** [comment]
@kerchner I'm making the presumption that it is then OK to merge this PR.  I'm going to proceed so that I can get the next PR rebased and ready to go.  Hoping this is acceptable.

**Comment by kerchner** [comment]
:+1:

**Pull request merged**
