### PR TITLE
T1012 postgres upgrade

### PR DESCRIPTION
**Pull request by lwrubel**
Steps to set up and test:
1. Make a backup of the existing 9.4 database. In sfm-docker/:
`docker exec sfm_db_1 pg_dumpall -U postgres > pgdump`
Review it: 
`cat pgdump | less`
2. `docker-compose stop`
3.  `docker-compose rm -v db`
4. update docker-compose.yml to build the image for db.
```
    db: 
        build: 
            context: ../sfm-ui/docker/db 
            dockerfile: Dockerfile
       #image: gwul/sfm-ui-db:master
```
5. Create a postgres 9.6 database with just the default database, this triggers initdb running and creating a pg_hba.conf file with the correct permissions. Use the absolute path for your sfm-data/postgresql directory, this example uses mine:

```
docker run --name postgres -d -v /home/lwrubel/projects/sfm-data/postgresql/9.6/data:/var/lib/postgresql/data -e POSTGRES_PASSWORD=password postgres:9.6
```
5. `docker stop postgres`
6. `docker rm -v postgres`
7. Run the upgrade image, changing the sfm-data path to match yours:
```
docker run --rm \
    -v /home/lwrubel/projects/sfm-data/postgresql/data:/var/lib/postgresql/9.4/data \
    -v /home/lwrubel/projects/sfm-data/postgresql/9.6/data:/var/lib/postgresql/9.6/data \
tianon/postgres-upgrade:9.4-to-9.6
```
8. Bring up the db container based on the new image:
`docker-compose up --build -d`

### CODE REVIEW

**Comment by lwrubel** [comment]
If things get messed up, I have steps for restoring to 9.4 using the copy of the database dumped earlier.

**Comment by dolsysmith** [comment]
Upgrade to 9.6 completed successfully. 

One question I have: should the change to docker-compose.yml -- replacing the image with the build -- remain after completing the upgrade and bringing up the new container?

**Comment by lwrubel** [comment]
Once this is merged into master and Docker Hub has built a new master image, if will be OK to use that instead of locally building the image. 

BTW, I'm also writing step-by-step instructions for the release notes, so that existing SFM installations can upgrade their database as part of the upgrade. 

When you've been able to test functionality in SFM with this branch and all is well, let me know so that I can manually squash the changes and push them.

**Comment by dolsysmith** [comment]
Everything seems to work in the UI -- harvesting and exporting.

**Pull request merged**
