### PR TITLE
Add New Collection form and tests

### PR DESCRIPTION
**Pull request by lwrubel**

### CODE REVIEW

**Comment by kerchner** [comment]
- Instead of setting `self.fields['name'].label = 'Collection name'`, use `verbose_name` in the model field.  We observed that crispy forms does pick up the verbose_name.
- In `CollectionForm`, `is_valid`, `full_clean`, `save` are not doing anything, so they should be removed. We can put back if we opt to override.

**Comment by kerchner** [comment]
Refs Issue #96

**Comment by kerchner** [comment]
@lwrubel on my instance, the Cancel button on /ui/collections/create/ doesn't do anything.  Does it work for you?

**Comment by lwrubel** [comment]
The cancel button should be good now. Thanks for catching that.

**Pull request merged**
