### PR TITLE
refs #123. Adds README to exports and management command to generate …

### PR DESCRIPTION
**Pull request by justinlittman**
…READMEs. refs #377. Displays seed change log on collection page.

### CODE REVIEW

**Comment by justinlittman** [comment]
Suggestions for testing README:
1.  Create an export.
2.  Observe that a README.txt is included in the export.  Check the content of the README.

Suggestions for testing change log:
1.  Go to a collection detail page which has seeds.
2.  Observe that change logs includes changes of collection and seeds.  What is being changed is indicated by Change to column.

**Comment by lwrubel** [comment]
Comments on README:
* README is showing, "Format: export.export_format" when it should be "CSV" (or other format selected). 
* This is minor, could be addressed later, but the harvest options are in a different order than the UI. 
* Date created is not same timezone: "Created on Dec. 15, 2016, 8:32 a.m." when it was created at 1:32 p.m.

**Comment by lwrubel** [comment]
I'm getting an error when trying an export where the collection has more than one seed. 
```
Exception Type:	TypeError
Exception Value:	
'str' object is not callable
Exception Location:	/opt/sfm-ui/sfm/ui/forms.py in label_from_instance, line 793
```

for line:

`{% for choice in field.field.choices %}`

**Comment by lwrubel** [comment]
{{ item.collection.collection_set.name }} is displaying instead of the collection_set name in breadcrumbs at for seed change_log pages. Django doesn't seem to like line breaks in template variables.

**Comment by justinlittman** [comment]
@lwrubel Fixed problems that you reported.

**Pull request merged**
