### PR TITLE
refs #224. Adds stats rollup and display for seed sets and collections.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
To test:
1. Create and start harvests of one or more seed sets.
2. Wait for harvests to be performed.
3. Observe counts of items harvested on collection and seed set detail pages.

**Comment by justinlittman** [comment]
@rajatvij - Sorry, but I realized that the stats fields were never changed to JSONFields.

**Comment by rajatvij** [comment]
@justinlittman The stats that i am able to see for individual harvest types are as follows:

Flickr User harvest - users and photos
Twitter timeline - tweets and web resources. Are not expecting photos here?
Twitter Search - Nothing. Are we not expecting anything for twitter search?

Please let me know if i should expect something else.
As far as the code related to the ticket is concerned, this seems to be working fine as it is displaying all stats from summary section of harvest return message. I just want to double check on what should be returned in summary section of each harvest success message.

**Comment by justinlittman** [comment]
Good point.  The names of the stats items is confusing.  I'm going to clarify (e.g., "Flickr photos" instead of just "photos".)

You should see tweets for Twitter search.  I'll test and see if I can replicate -- I suspect you may have just had a problem with your search.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-flickr-harvester/commit/9f2993f8ea4f48e74a20935c4d5c079f21cd634b tweaks the stats for Flickr.

**Comment by justinlittman** [comment]
I've verified that search correctly returns tweets.  I'm going to go ahead and rebase/merge.

**Pull request merged**
