### PR TITLE
refs #208. Renames collection to collection set and seedset to collec…

### PR DESCRIPTION
**Pull request by justinlittman**
…tion.

### CODE REVIEW

**Comment by lwrubel** [comment]
ChangeLogView in `views.py` uses apps.get_model and it's expecting the exact model name. 
```
ModelName = apps.get_model(app_label="ui", model_name=model_name)
```
So /ui/collection_set/2/changes/ does not work but /ui/collectionset/2/changes/ does work. I don't think we use this anywhere else, so we could change the view to handle collection_set, rather than change urls.

**Comment by lwrubel** [comment]
Or change the model_name passed in the context data.

**Comment by lwrubel** [comment]
I'm seeing some seedset references in the docs, specifically messaging_spec.rst and processing.rst, and harvester.rst might need an quick check of the WARC path.

**Comment by justinlittman** [comment]
@lwrubel Can you double check that you're looking at the right branch for the docs?  I'm not seeing any errant seedset references.

**Comment by lwrubel** [comment]
@justinlittman You're right, I was looking at the wrong branch. Sorry about that.

**Comment by lwrubel** [comment]
@justinlittman that latest commit fixes getting to the change log page for a collection set, but the breadcrumbs in the change_log.html template are looking for "collection_set" and are not displaying. 

The h2 should probably also say "collection set" rather than "collectionset". But that can go in another ticket if needed.

**Pull request merged**
