### PR TITLE
refs #479. Adds support for deleting collections, etc.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
Steps for testing:
1.  Create collection sets, collections, and exports.
2.  Check that the files exist in /sfm-data.
3.  Log into Admin and delete them.
4.  Check that the files no longer exist.

Test with Apache and runserver.

**Comment by adityadharne** [comment]
@justinlittman I am getting a `[Errno 30] Read-only file system` error. Should I change permissions for the directory?

**Comment by justinlittman** [comment]
In your docker-compose.yml make sure that the volumes that are linked into the ui container are not marked "ro".

```
        volumes_from:
            - data
            - processingdata
```

**Comment by adityadharne** [comment]
Delete works. Merging

**Pull request merged**
