### PR TITLE
T92 scheduler

### PR DESCRIPTION
**Pull request by justinlittman**
refs #92

### CODE REVIEW

**Comment by kerchner** [comment]
@justinlittman Reading through the code, it looks good, but this branch needs a rebase/merge.  Hopefully that will resolve the CI build as well as the two tests that are currently failing for me.

**Comment by justinlittman** [comment]
@kerchner - This is rebased and passing unit tests.  Do you want me to merge or do you want to test/review further?

**Comment by kerchner** [comment]
@justinlittman I opted to stop my initial testing once I realized the need for a rebase.   Unless you think this PR doesn't warrant testing, I'll proceed with the updated branch.

**Comment by justinlittman** [comment]
I'd suggest testing.

**Comment by justinlittman** [comment]
@kerchner - rebase completed.

**Comment by kerchner** [comment]
:+1:

**Pull request merged**
