### PR TITLE
Collection detail view with seedset table. Fixes #97.

### LINKED ISSUE #97: Update collection_detail along lines of wireframe
* Note this includes a list of seedsets.
* Need to be able to edit information here.
* May need to create placeholder for changelog; changelog work should be ticketed separately?

### PR DESCRIPTION
**Pull request by lwrubel**
Note there are commented-out placeholders in the template for information which will be derived from the harvest status message.

### CODE REVIEW

**Comment by kerchner** [comment]
- When creating a SeedSet, I would recommend passing the Collection ID via the request rather than in the URL.  Also, a URL like "ui/seedsets/<collection number>/create/" doesn't seem right; the number might be interpreted as the id for the new seedset.
- The Edit button is off in the upper right, which feels like a non-obvious place.  Is there a place it could reside that would be closer to where the focus of the page is, i.e. closer to the content?

**Comment by lwrubel** [comment]
@kerchner the "add seedset" button form is passing the collection id via get. When I tried to do it via post, it tries to submit the seedset form. I'd welcome advice on this, I've probably been struggling too long on this ticket. Also, if I should squash and push again, let me know.

**Comment by lwrubel** [comment]
@kerchner please re-review

**Comment by kerchner** [comment]
- On collection edit page, the Add Seedset button is disabled because I assume we don't want the user leaving the collection details while they're open for editing.  However, the Seedsets in the Seedset list are clickable, and this would take the user off the collection edit page.  Do we want to consider not rendering the seedset names as links?
- Otherwise, looks good.

**Comment by lwrubel** [comment]
I can go either way on that. I thought it might be useful for gathering
info that would inform the description or name edits. The links at least
don't go straight to a form, but to a DetailView. Maybe we could leave this
as is and then as we start using it, see how if it makes sense still?

**Comment by kerchner** [comment]
:+1: Please squash, then I'll merge

**Pull request merged**
