### PR TITLE
T552 data dictionary

### PR DESCRIPTION
**Pull request by kerchner**
This requires https://github.com/gwu-libraries/sfm-twitter-harvester/pull/28 in order for the data dictionary and the twitter export to match.

### CODE REVIEW

**Comment by kerchner** [comment]
Also note that this PR is not just text changes; it also implements readthedocs config and stylesheet enhancements to enable the table to behave responsively.  By default, the readthedocs template results in tables that are fixed-width with a horizontal scroll bar, and thus often difficult to read.

**Comment by kerchner** [comment]
@yonahbg This is ready for review and merge.

**Comment by justinlittman** [comment]
@yonahbg If you have questions about what this entails or how to do it, let me know.

**Comment by kerchner** [comment]
@yonahbg are you sure you've updated your branch to reflect the changes pushed 2 days ago?

**Comment by kerchner** [comment]
(@yonahbg) and that you've redone your `make html` ?

**Pull request merged**
