### PR TITLE
T44 scheduling

### PR DESCRIPTION
**Pull request by rajatvij**
Given user option to schedule harvest update seedset messages by daily, hourly or per minute basis within the start and end dates.

We need to check if start and end date our working correctly or not as i wasn't able to test that properly.

### CODE REVIEW

**Comment by kerchner** [comment]
@rajatvij It looks like you need to resolve branch conflicts here.

**Comment by kerchner** [comment]
@rajatvij are there any particular steps I will need in order to test this?

**Comment by rajatvij** [comment]
@kerchner Nope. Just make sure to put correct start and end date in seed update page to test this and it should work in similar way our master works.

**Comment by kerchner** [comment]
@rajatvij I see that git was added to app-dev/Dockerfile.  Why is git needed?

**Comment by rajatvij** [comment]
@kerchner Sorry, that was for when i was trying different schedulers from github and adding them in requirement.txt but it is not needed now. I just forgot to remove it.

**Comment by kerchner** [comment]
@rajatvij Please make start and end date:
- optional, and
- just dates, not date-times
assuming that you verify that apscheduler is expecting them as just dates

**Comment by kerchner** [comment]
@rajatvij As currently written, if you create a SeedSet with a schedule, SFM adds the job to the scheduler.  However, if you then go back and modify the SeedSet, SFM adds a new job to the scheduler, but the first job is still there.  You'll want to either:
- Modify the job (using modify_job), or
- Remove the job, then re-add.

**Comment by kerchner** [comment]
@rajatvij fyi i've updated the queue name in https://github.com/gwu-libraries/sfm-ui/pull/76

**Comment by rajatvij** [comment]
For now, when we are modifying an existing job, it gets executed twice.
It seems they had a design flaw related to this which they fixed in an older version. Here is the link to their readthedocs mentioning this :  https://apscheduler.readthedocs.org/en/v2.0.0/

**Comment by kerchner** [comment]
@rajatvij note that there are merge conflicts (the button is not green)

**Comment by justinlittman** [comment]
I've got some commits pending.

**Comment by justinlittman** [comment]
I think @dchud hypothesis is correct -- there are multiple instances of the scheduler running.  Notice there are 2 pids in this log:

```
[Wed Dec 09 17:11:47.206219 2015] [:error] [pid 185:tid 140675960162048] Instantiating scheduler
[Wed Dec 09 17:11:47.206591 2015] [:error] [pid 185:tid 140675960162048] Starting scheduler
[Wed Dec 09 17:11:47.206841 2015] [:error] [pid 185:tid 140675960162048] Scheduler started
[Wed Dec 09 17:11:47.220891 2015] [:error] [pid 185:tid 140675815307008] Looking for jobs to run
[Wed Dec 09 17:11:47.221028 2015] [:error] [pid 185:tid 140675815307008] No jobs; waiting until a job is added
[Wed Dec 09 17:11:50.528834 2015] [:error] [pid 186:tid 140675951769344] Instantiating scheduler
[Wed Dec 09 17:11:50.529149 2015] [:error] [pid 186:tid 140675951769344] Starting scheduler
[Wed Dec 09 17:11:50.529362 2015] [:error] [pid 186:tid 140675951769344] Scheduler started
[Wed Dec 09 17:11:50.538628 2015] [:error] [pid 186:tid 140675815307008] Looking for jobs to run
[Wed Dec 09 17:11:50.538740 2015] [:error] [pid 186:tid 140675815307008] No jobs; waiting until a job is added
[Wed Dec 09 17:11:50.758110 2015] [:error] [pid 186:tid 140675951769344] None
[Wed Dec 09 17:11:50.758163 2015] [:error] [pid 186:tid 140675951769344] Jobstore default:
[Wed Dec 09 17:11:50.758175 2015] [:error] [pid 186:tid 140675951769344]     No scheduled jobs
[Wed Dec 09 17:11:50.758224 2015] [:error] [pid 186:tid 140675951769344] Adding 1
[Wed Dec 09 17:11:50.776126 2015] [:error] [pid 186:tid 140675951769344] Added job "<lambda>" to job store "default"
[Wed Dec 09 17:11:50.820390 2015] [:error] [pid 186:tid 140675815307008] Looking for jobs to run
[Wed Dec 09 17:11:50.820613 2015] [:error] [pid 186:tid 140675815307008] Next wakeup is due at 2015-12-09 17:12:00+00:00 (in 9.179522 seconds)
[Wed Dec 09 17:11:54.842915 2015] [:error] [pid 185:tid 140675960162048] None
[Wed Dec 09 17:11:54.842974 2015] [:error] [pid 185:tid 140675960162048] Jobstore default:
[Wed Dec 09 17:11:54.842985 2015] [:error] [pid 185:tid 140675960162048]     No scheduled jobs
[Wed Dec 09 17:11:54.843036 2015] [:error] [pid 185:tid 140675960162048] Adding 1
[Wed Dec 09 17:11:54.857039 2015] [:error] [pid 185:tid 140675960162048] Added job "<lambda>" to job store "default"
[Wed Dec 09 17:11:54.890674 2015] [:error] [pid 185:tid 140675815307008] Looking for jobs to run
[Wed Dec 09 17:11:54.890902 2015] [:error] [pid 185:tid 140675815307008] Next wakeup is due at 2015-12-09 17:12:00+00:00 (in 5.109255 seconds)
```

So it looks like it is necessary to change the approach to instantiating the scheduler.

**Comment by kerchner** [comment]
@justinlittman did you observe a parent-child process relationship between the two processes.  I.e. is 185 the ppid (parent pid) of 186?  Or are they both children of a common parent pid?

**Comment by justinlittman** [comment]
Unclear. I just saw the different pids in the apscheduler logs.

**Comment by justinlittman** [comment]
You'll also notice that the log shows the creation of 2 schedulers (one in each pid). @kerchner - can you suggest what is the correct django way to handle start-up of the scheduler so it is a singleton?

**Comment by justinlittman** [comment]
Also @rajatvij - I noticed some minor PEP8 issues that need to be fixed.

**Pull request merged**
