### PR TITLE
T220 hide request export button. closes #220

### LINKED ISSUE #220: Request export button not display until there is a successful harvest
This avoids a situation where an export fails because there are no harvests completed and/or no WARCs yet.

### PR DESCRIPTION
**Pull request by rajatvij**
This disables the "Request Export" button on Seedset detail screen where harvest for the seedset is incomplete, failed or has not started yet.

Steps to Test:
1. Log in to sfm-ui, create credentials, and collection. Add seedset to the collect.
2. Go to seedset details screen and check if the request export button is disabled.
3. Add seeds to the seedset and update seedset to initiate a harvest or initiate a harvest from admin.
4. After a minute when the harvest is completed. Check if the harvest's status is completed successful. If so, then the "Request Export" button should be enabled on Seedset details screen.

### CODE REVIEW

**Comment by lwrubel** [comment]
@rajatvij When I click on a seedset from a collection_detail view, I get an error that seems to go back to this line: 
`if Harvest.objects.get(harvest_type=self.object.harvest_type).status == "completed success":
`

The error is something like: 
"get() returned more than one Harvest -- it returned 902!"

Would filter() accomplish what you need here? I think what you're really trying to do is see if at least one has status == "completed success" 

While you're in there working on this, you can simplify the template if/else logic by just putting the following in the button HTML:
`{% if not can_export %} disabled {% endif %}
`

**Comment by rajatvij** [comment]
@lwrubel I have fixed the issue, please check and let me know if any other changes are required.

**Comment by lwrubel** [comment]
@rajatvij, the user should be able to request an export as long as there is one "completed success" harvest. Right now, the status of the last harvest is what is determining the availability of the request export button. I have a seedset with many harvests, some of which have completed successfully, but because the more recent ones have not completed, I don't get the button.

How about instead, checking to see if there is at least one "completed success"?  You could break out of the loop once one is found, so you don't have to check every single harvest.

**Comment by rajatvij** [comment]
@lwrubel sorry, i misinterpreted the ticket before. I have corrected the condition now. Please check and let me know if you find any other issue with the ticket.

**Comment by kerchner** [comment]
@lwrubel It looks like the merge for #236 may have caused merge conflicts that need to be resolved.

**Comment by lwrubel** [comment]
@rajatvij, would you review the merge conflicts and fix?

**Comment by rajatvij** [comment]
@lwrubel I have rebased the branch with master to fix merge conflicts.

**Comment by lwrubel** [comment]
@rajatvij It looks like that old line of SeedSetUpdateView snuck into views.py. Would you replace 
`context["collection"] = Collection.objects.get(pk=self.kwargs["collection_pk"])`
with
`context["collection"] = Collection.objects.get(pk=self.object.collection.pk)`
then squash?

**Comment by lwrubel** [comment]
@rajatvij when I try to edit a seedset, I still get a KeyError because of line 194 of views.py 
`kwargs['credential_list'] = _get_credential_list(self.kwargs["collection_pk"], self.kwargs["harvest_type"])`

**Comment by rajatvij** [comment]
@lwrubel Sorry, I introduced that issue while resolving merge conflicts. I have corrected that, this should be ok to merge now.

**Pull request merged**
