### PR TITLE
Ref #640 #727 seed duplicate for twitter user timeline

### PR DESCRIPTION
**Pull request by Tanych**
Adding validation rule for twitter user timeline.
* checking duplicate when create and update
* checking null when create and update
* allow udpating status 

Ref #640, For detail test cases, please check the issue page.
Ref #727, seed value error

### CODE REVIEW

**Comment by kerchner** [comment]
Also note related issue #714

**Comment by Tanych** [comment]
@justinlittman  it's ready for test!

**Comment by justinlittman** [comment]
In this case (1) "One of the following fields is required :Screen name User id." shouldn't be displayed and (2) the wording should be correct ("One of the following fields is required: Screen name or User id.")

screen shot 2017-03-06 at 3 05 28 pm

**Comment by justinlittman** [comment]
After that fix and a rebasing, it is good to go.

**Comment by Tanych** [comment]
@justinlittman fixed, if it's good to go, please merge and close

**Comment by kerchner** [comment]
@justinlittman @Tanych Before merging, note the case I added to #640 - may require additional work (or not, see what you think).

**Pull request merged**
