### PR TITLE
T1011 datetime picker

### PR DESCRIPTION
**Pull request by lwrubel**
To test:
1. Do an export and select item start / item end dates (and times).
2. Do an export and select harvest start / harvest end dates (and times).
3. Create a collection and set an end date on the collecting. 

The dates should be reflected in the export.

### CODE REVIEW

**Comment by dolsysmith** [comment]
Export with item and harvest start/end date and time working as expected. There is a bit of a bug, however: if you enter a date/time in one of the fields and then decide that you actually want to leave that field blank, you can delete the date/time value. In fact, when I accidentally clicked in the harvest start date field, it inserted a date and time, and I was unable to remove it (except by cancelling the whole export and starting over).

**Comment by lwrubel** [comment]
Good catch! It looks like flatpickr has a "clear" option to add onto a field. I will look and see how that might work with django-crispy-forms in these fields.

**Comment by lwrubel** [comment]
@dolsysmith In addition to making the date fields clearable, I've set the default time to be 00:00 instead of 12:00, which seems like it would better align with what people are expecting to export.

**Comment by lwrubel** [comment]
Looks good. I was able edit and delete dates and times. After picking a date and time, I then deleted the time, and 00:00 was restored when a datetime object was created. Tested in the export and collection edit forms. I'll squash and merge.

**Pull request merged**
