### PR TITLE
T117 harvest status

### PR DESCRIPTION
**Pull request by justinlittman**
refs #117.

### CODE REVIEW

**Comment by justinlittman** [comment]
A few notes:
* It is based on the #54 branch so that it can add a note to the log entry when updating a seed.
* I deleted the existing migrations and created a new one.  The migration required to use a jsonfield was complicated and would have required some fiddling by hand.  Since no one is actually migrating an existing db, it was far easier to start fresh.

To test this:
1. Bring up an sfm-ui and a harvester.  Here's the docker-compose.yml I used:
```
sfmdevdb:
    image: gwul/sfm-ui-db:master
    environment:
        - POSTGRES_PASSWORD=gherD42#dl5
sfmdevapp:
    image: gwul/sfm-ui:dev
#    build: app-dev
    ports:
        - "8081:80"
    links:
        - sfmdevdb:db
        - sfmdevrabbit:mq
    environment:
        - SFM_DEBUG=True
        - SFM_APSCHEDULER_LOG=DEBUG
#        - SFM_DJANGO_LOG=DEBUG
        - SFM_UI_LOG=DEBUG
    volumes:
        - ~/Data/sfm3/sfm-ui:/opt/sfm-ui
sfmdevrabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmmflickrharvester:
    image: gwul/sfm-flickr-harvester:0.2.0
    links:
        - sfmdevrabbit:mq
    restart: always
```
2. Kick off a harvest by creating credentials, seed set, and seed.
3. Look at harvests in the admin site.

Expected results:
* A harvest is created when the harvest start message is sent.
* The harvest is updated when the harvest status message is received.
* Seeds are updated if the harvest status message contains updates.

**Comment by kerchner** [comment]
@justinlittman :+1: seems to work.   Can I infer that you updated gwul/sfm-ui-db:master so that it reflects the result of the db migration in this PR?  I certainly didn't point my docker-compose.yml to any branch of gwul/sfm-ui-db.

**Comment by kerchner** [comment]
@justinlittman Did you also want to remove ` +git+https://github.com/gwu-libraries/django-auditlog.git@master#egg=django-auditlog` from requirements.txt as part of c1ad272d25ca182ff230d21471ae6cf5debced52?   No harm in leaving it in there, I suppose, but I'm guessing you would have wanted to back that out too.

**Comment by justinlittman** [comment]
@kerchner gwul/sfm-ui-db:master is a blank database, so need to update.

Removing django-auditlog.git in following commit.

**Pull request merged**
