### PR TITLE
T99 seedset detail

### PR DESCRIPTION
**Pull request by lwrubel**
Note that this has no new tests, pending conversation with @justinlittman about django testing.

### CODE REVIEW

**Comment by kerchner** [comment]
@lwrubel :+1: please proceed with squash

**Comment by lwrubel** [comment]
In process of resolving merge conflicts, which have to do with introduction of diffs / history support added since this PR created.

**Comment by lwrubel** [comment]
@kerchner introduction of history support requires some further UI work. I've made sure it displays, but the layout needs refinement. Rather than prolonging this PR, I'd suggest creating a new ticket for that UI work.

**Comment by kerchner** [comment]
Layout tweaks will be addressed in https://github.com/gwu-libraries/sfm-ui/issues/156

**Pull request merged**
