### PR TITLE
refs #274. Updates apscheduler version. Only starts apscheduler for s…

### PR DESCRIPTION
**Pull request by justinlittman**
…fm-ui. Removes extra apache starts.

### CODE REVIEW

**Comment by justinlittman** [comment]
@Tanych To test this, you'll need to build the container.

So in your docker-compose.yml, this would be something like:
```
sfmuiapp:
    build: app-dev
```
and then run `docker-compose build` to build the container.

**Comment by Tanych** [comment]
### Test case

## sfmuiapp build without cache
* Frequency: 1 minute
* Results: Running the harvester per minute, there are `no duplicate logs` for the 20 harvesters.

Restart the containers 
## sfmuiapp build with cache
* Frequency: 1 minute
* Results: Running the harvester per minute, there are `no duplicate logs` for the 30 harvesters.

It might be the running frequency time for the test case

## sfmuiapp build with cache
* Frequency: 30 minutes
* Results: Running the harvester per 30 minutes, it frequently occurs`duplicate logs` for the harvesters.

## sfmuiapp build without cache
* Frequency: 30 minutes
* Results: Running the harvester per 30 minutes, `waiting for more data to review the testing`.

**Comment by Tanych** [comment]
@justinlittman  I think building with no cache might be the answer for this bug. It runs well for one night.

**Comment by justinlittman** [comment]
@Tanych Excellent.  OK to merge this PR?

**Comment by Tanych** [comment]
@justinlittman  Based on the 24 hours running, I think it can merge the PR.

**Comment by justinlittman** [comment]
@Tanych I will rebase and merge.  Thanks for your persistence on this!

**Comment by Tanych** [comment]
OK. I will keep running the testing demo.

**Pull request merged**
