### PR TITLE
Fixes #273. Notifications on login and export pages.

### LINKED ISSUE #273: preliminary language about terms of use
At a minimum, adapt language on "old" SFM to new SFM, to appear on login page, export page, and possibly others, alerting users about platforms' terms of use / ethical concerns. (In future, point to a more in-depth discussion on this within Help.)

### PR DESCRIPTION
**Pull request by lwrubel**

### CODE REVIEW

**Comment by lwrubel** [comment]
Don't merge this yet, need to add the link to the project site.

**Comment by kerchner** [comment]
@lwrubel did you want to use:
- this link instead for Twitter's general policies?  https://twitter.com/rules
- this link instead for Twitter's developer policies? https://dev.twitter.com/overview/terms

@Tanych are there comparable links for Sina Weibo, for:
- General terms of use / policies (similar to twitter.com/rules )
- Developer terms of use / policies (similar to dev.twitter.com )
?

**Comment by kerchner** [comment]
@lwrubel also not crazy about the location of the text on the Export page.  Let's adjust that in a later release, but there's plenty of width to spare given that those export field values are not lengthy; perhaps we could put the text side-by-side with the fields (again, in a future release).

**Comment by justinlittman** [comment]
I would suggest using a bootstrap well (http://getbootstrap.com/components/#wells) for the terms.

Also, who is the "we" in "We provide data to you"?  Is it the authors of SFM (i.e., us) or the institution running SFM?  I would suggest "SFM is intended to collect data for your research and academic use."

**Comment by lwrubel** [comment]
@kerchner, thanks, I think those links are better for terms.
@justinlittman, experimenting with wells, that is an improvement.

I'll adjust the "we" but when this version of SFM is up as a GW Libraries service, would like to review this. I was thinking of the voice of the organization providing this as a service. Possibly that doesn't fit here, maybe at the entry point. 

I agree this will need further work post 1.0.

**Comment by kerchner** [comment]
@lwrubel : as per advice of @Tanych ,
General use terms: http://www.weibo.com/signup/v5/protocol 
and
Developer/API terms:  http://open.weibo.com/wiki/%E9%A6%96%E9%A1%B5

**Comment by lwrubel** [comment]
@kerchner ready for review again

**Comment by lwrubel** [comment]
Looks like a file from the gh-pages branch got added here, which is a mistake. Let me fix that.

**Comment by lwrubel** [comment]
@kerchner fixed and took the opportunity to make the terms open in different window/tab

**Pull request merged**
