### PR TITLE
T134 warc created

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
For testing:
* In Admin, notice that Media is now Warcs.
* In Admin, notice that Collections, Seedsets, Seeds, and Harvests now have automatically generated id fields which are UUIDs.
* Submit a warc_created message and notice how a Warc model object is created.
* In Admin, create an Export model object and notice how an export start message is submitted.
* Submit an export status message and notice how Export model object is updated.
* Explore the REST API at `http://<base url>/api/v1/`, noting that only warcs are exposed.

**Comment by kerchner** [comment]
@justinlittman it looks like this has merge conflicts

**Comment by justinlittman** [comment]
@kerchner Conflicts fixed.

**Comment by kerchner** [comment]
(will be re-editing to track progress reviewing this PR)

- [X] In Admin, notice that Media is now Warcs.
- [X] In Admin, notice that Collections, Seedsets, Seeds, and Harvests now have automatically generated id fields which are UUIDs.
- [ ] Submit a warc_created message and notice how a Warc model object is created.
- [ ] In Admin, create an Export model object and notice how an export start message is submitted.
- [ ] Submit an export status message and notice how Export model object is updated.
- [ ] Explore the REST API at http://<base url>/api/v1/, noting that only warcs are exposed.

**Comment by kerchner** [comment]
Review is currently blocked pending resolution of #167

**Comment by kerchner** [comment]
I'll need to go back to better understand the Filters code for the API, but it seems to work.
Reviewed code, ran ./manage.py test, successfully executed functional tests (after much wrangling with docker-compose configuration).
:+1:

**Pull request merged**
