### PR TITLE
Ref #725 adding weibo description

### PR DESCRIPTION
**Pull request by Tanych**
Ref #725, adding weibo search collection description and remove the hard code for the UX for collection description.

### CODE REVIEW

**Comment by Tanych** [comment]
@justinlittman  can you take 2 minutes to review this PR? If it's OK, merge it and close the ticket.

**Comment by Tanych** [comment]
@adityadharne Well, I think It makes more general and flexible to add harvester type. Weibo harvester is a special case that it only turns on when people want to. Also, it won't alter model and do migrations, it's just a class member. As the general process, all the process should do on the view level. The templates are hard to control the process and back-end logical.

**Comment by adityadharne** [comment]
@Tanych No, I meant this can be done in a later ticket- There are alterations to that ticket which are not in master yet. It will cause merge conflicts.

**Comment by Tanych** [comment]
@adityadharne OK, you can go ahead, and  I will fix the conflicts if necessary.

**Comment by kerchner** [comment]
Dependent on merging #731 .  May requires rebase.

**Comment by kerchner** [comment]
@Tanych Requires rebase (probably due to my merging #713)

**Comment by Tanych** [comment]
@kerchner  It could be #731. The UX change. Now, it fixed.

**Pull request merged**
