### PR TITLE
Ref #379 adding weibo search

### PR DESCRIPTION
**Pull request by Tanych**
Ref https://github.com/gwu-libraries/sfm-ui/issues/379 Ref https://github.com/gwu-libraries/sfm-ui/issues/630 Ref https://github.com/gwu-libraries/sfm-weibo-harvester/pull/27
* optional adding weibo search in collection
* adding weibo search seeds

### CODE REVIEW

**Comment by kerchner** [comment]
@Tanych I'm sorry for taking so long to review this.  In the meanwhile, it looks like models.py now conflicts with master.  Can you please resolve the conflict and then I'll be able to review?

**Comment by kerchner** [comment]
@Tanych Please add `WEIBO_SEARCH_OPTION` to https://github.com/gwu-libraries/sfm-docker/blob/master/example.env so that `sfm/sfm/settings/common.py` can pull it from the environment if present in the .env file

**Comment by Tanych** [comment]
@kerchner there is an PR for sfm-docker. You can see the details for the PR test at [here](https://github.com/gwu-libraries/sfm-ui/issues/379#issuecomment-281456083).

**Comment by kerchner** [comment]
@Tanych My mistake - I see now that you referenced #630 above.  I'll pull that branch from sfm-docker.

**Comment by Tanych** [comment]
@kerchner it's ok. It involves lots of things, so I made a list PR for you.

**Comment by kerchner** [comment]
✅  Verified that Weibo search works, and that `SFM_WEIBO_SEARCH_OPTION` controls show/hide of this collection type.

**Pull request merged**
