### PR TITLE
Refs #378 add public weibo timeline description

### PR DESCRIPTION
**Pull request by Tanych**
Ref #378 , to make the demo description more clear.

### CODE REVIEW

**Comment by justinlittman** [comment]
Looks like you have some extra commits in this PR.

**Comment by Tanych** [comment]
@justinlittman , this PR includes fixing the Travis buildings and an external link that it's invalid, both are tiny change. I didn't separate them.

**Comment by justinlittman** [comment]
So what I think Nich was asking for is a description of friends timeline.  That is, it would be helpful to add another section describing what harvest we do with the weibo harvester (i.e., a friends timeline) and how it works.  (For example, that you have to follow the people whose weibos you want collect.)

Ideally, we should have a section in the user docs for this, but in the meantime a small addition to the blog post will suffice for explaining it for weibo.

**Comment by justinlittman** [comment]
Also, I've reviewed everything that is committed to this branch so far and it is good to go.

**Comment by Tanych** [comment]
Ok, I would add the section including the `friend timeline`.

**Pull request merged**
