### PR TITLE
T227 iteration env

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by kerchner** [comment]
@justinlittman It looks like the merge for #236 may have caused merge conflicts that need to be resolved.

**Comment by justinlittman** [comment]
@kerchner Rebased and fixed conflicts.

**Comment by kerchner** [comment]
@justinlittman please resolve merge conflicts

**Comment by justinlittman** [comment]
@kerchner Done.

**Comment by kerchner** [comment]
@justinlittman I was able to successfully process twitter warcs and generate a word cloud as per the example.  However:
- The instantiation instructions under "Approaches" (in `processing.rst`) seems to fail because the `processing/Dockerfile` has an explicit dependency on `/opt/sfm-twitter-harvester` which will not be present unless you also add it with `--volumes-from` the twitter harvester container, etc.
- As a result, I found it more useful/realistic to follow the instructions in https://github.com/gwu-libraries/sfm-docker/blob/sfm_227-iteration_env/docker/dev/processing/Dockerfile#L23-L27  (and consider making the file paths less /Users/justinlittman-specific).   Would it be useful to push some of this information up to `processing.rst`?  And/or to `prod/processing/Dockerfile` etc.?
- Note that `twitter_rest_warc_iter.py` is not executable as installed.  Consider either `+x`ing the file mode (and pushing to the t227 branch) or modifying examples in processing.rst to specify `python twitter_rest_iter.py`.

I also tried adding sfm-flickr-harvester to my processing environment.  This was successful but required:
- extending `processing/Dockerfile`  - consider adding steps for including flickr and Weibo, at least in the form of comments.
- Suppressing warcprox from the sfm-flickr-harvester requirements.  See #288.

**Comment by kerchner** [comment]
Additionally:  Following the local setup instructions yielded the following when running `twitter_rest_warc_iter.py`:

   `ImportError: No module named dateutil.parser`

Is there another dependency that should be included?

**Comment by justinlittman** [comment]
@kerchner:
* The dependency on `/opt/sfm-twitter-harvester` only exists for the dev container. The other containers already contain the sfm-twitter-harvester code.
* I would suggest not pushing the additional instructions into `processing.rst` since they only apply to the dev container.  Once this is merged, we'll start automatically building the master and production version of these containers.  We would expect a user to use master or production, not dev.
* I can't replicate the problems with `twitter_rest_warc_iter.py`:
```
root@a67426c5241c:/sfm-data# twitter_rest_warc_iter.py
usage: twitter_rest_warc_iter.py [-h] [--pretty] [--dedupe]
                                 [--print-item-type] [--debug [DEBUG]]
                                 filepaths [filepaths ...]
twitter_rest_warc_iter.py: error: too few arguments
```
I suspect it may have something to do with your environment.  Are you on `sfm_227-iteration_env` for sfm-utils and `master` for sfm-utils?  Have you pulled the latest?

Sorry this is not more straight-forward. Testing new containers is messy.

**Comment by kerchner** [comment]
@justinlittman the problem I am experiencing with twitter_rest_warc_iter.py (dateutil.parser problem) occurred in executing the steps under "Processing locally" i.e. on my Mac:
```
GLSS-M17LFFT:tmp kerchner$ which python2 | xargs virtualenv ENV -p 

Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /Users/kerchner/tmp/ENV/bin/python2.7
Not overwriting existing python script /Users/kerchner/tmp/ENV/bin/python (you must use /Users/kerchner/tmp/ENV/bin/python2.7)
Installing setuptools, pip, wheel...done.

GLSS-M17LFFT:tmp kerchner$ source ENV/bin/activate

(ENV) GLSS-M17LFFT:tmp kerchner$ pip install git+https://github.com/gwu-libraries/sfm-utils.git

Collecting git+https://github.com/gwu-libraries/sfm-utils.git
  Cloning https://github.com/gwu-libraries/sfm-utils.git to /var/folders/5b/1t0szdgn72b790hkpps8n7qrnc7837/T/pip-evxXhY-build
Collecting requests>=2.9.1 (from sfmutils==0.3.0)
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting kombu>=3.0.33 (from sfmutils==0.3.0)
  Using cached kombu-3.0.35-py2.py3-none-any.whl
Collecting supervisor>=3.2.0 (from sfmutils==0.3.0)
Collecting urllib3>=1.12 (from sfmutils==0.3.0)
  Using cached urllib3-1.15.1-py2.py3-none-any.whl
Collecting warc>=0.2.1 (from sfmutils==0.3.0)
Collecting petl>=1.1.0 (from sfmutils==0.3.0)
Collecting openpyxl>=2.3.3 (from sfmutils==0.3.0)
Collecting iso8601>=0.1.11 (from sfmutils==0.3.0)
  Using cached iso8601-0.1.11-py2.py3-none-any.whl
Collecting anyjson>=0.3.3 (from kombu>=3.0.33->sfmutils==0.3.0)
Collecting amqp<2.0,>=1.4.9 (from kombu>=3.0.33->sfmutils==0.3.0)
  Using cached amqp-1.4.9-py2.py3-none-any.whl
Collecting meld3>=0.6.5 (from supervisor>=3.2.0->sfmutils==0.3.0)
  Using cached meld3-1.0.2-py2.py3-none-any.whl
Collecting et-xmlfile (from openpyxl>=2.3.3->sfmutils==0.3.0)
Collecting jdcal (from openpyxl>=2.3.3->sfmutils==0.3.0)
Installing collected packages: requests, anyjson, amqp, kombu, meld3, supervisor, urllib3, warc, petl, et-xmlfile, jdcal, openpyxl, iso8601, sfmutils
  Running setup.py install for sfmutils ... done
Successfully installed amqp-1.4.9 anyjson-0.3.3 et-xmlfile-1.0.1 iso8601-0.1.11 jdcal-1.2 kombu-3.0.35 meld3-1.0.2 openpyxl-2.3.5 petl-1.1.0 requests-2.10.0 sfmutils-0.3.0 supervisor-3.3.0 urllib3-1.15.1 warc-0.2.1

(ENV) GLSS-M17LFFT:tmp kerchner$ pip install git+https://github.com/gwu-libraries/sfm-twitter-harvester.git

Collecting git+https://github.com/gwu-libraries/sfm-twitter-harvester.git
  Cloning https://github.com/gwu-libraries/sfm-twitter-harvester.git to /var/folders/5b/1t0szdgn72b790hkpps8n7qrnc7837/T/pip-v1Jn7w-build
Requirement already satisfied (use --upgrade to upgrade): sfmutils in ./ENV/lib/python2.7/site-packages (from sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.9.1 in ./ENV/lib/python2.7/site-packages (from sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): kombu>=3.0.33 in ./ENV/lib/python2.7/site-packages (from sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): supervisor>=3.2.0 in ./ENV/lib/python2.7/site-packages (from sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): urllib3>=1.12 in ./ENV/lib/python2.7/site-packages (from sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): warc>=0.2.1 in ./ENV/lib/python2.7/site-packages (from sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): petl>=1.1.0 in ./ENV/lib/python2.7/site-packages (from sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): openpyxl>=2.3.3 in ./ENV/lib/python2.7/site-packages (from sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): iso8601>=0.1.11 in ./ENV/lib/python2.7/site-packages (from sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): anyjson>=0.3.3 in ./ENV/lib/python2.7/site-packages (from kombu>=3.0.33->sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): amqp<2.0,>=1.4.9 in ./ENV/lib/python2.7/site-packages (from kombu>=3.0.33->sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): meld3>=0.6.5 in ./ENV/lib/python2.7/site-packages (from supervisor>=3.2.0->sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): et-xmlfile in ./ENV/lib/python2.7/site-packages (from openpyxl>=2.3.3->sfmutils->sfmtwitterharvester==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): jdcal in ./ENV/lib/python2.7/site-packages (from openpyxl>=2.3.3->sfmutils->sfmtwitterharvester==0.1.0)
Installing collected packages: sfmtwitterharvester
  Running setup.py install for sfmtwitterharvester ... done
Successfully installed sfmtwitterharvester-0.1.0

(ENV) GLSS-M17LFFT:tmp kerchner$ twitter_rest_warc_iter.py

Traceback (most recent call last):
  File "/Users/kerchner/tmp/ENV/bin/twitter_rest_warc_iter.py", line 5, in <module>
    from dateutil.parser import parse as date_parse
ImportError: No module named dateutil.parser
```

**Comment by justinlittman** [comment]
@kerchner:  I can reproduce.  Fixed by https://github.com/gwu-libraries/sfm-twitter-harvester/commit/407c3f9e5171509ea44491ed2bc3e47ac9c859dc.

**Comment by kerchner** [comment]
@justinlittman regarding executing `twitter_rest_warc_iter.py` inside the container:

I instantiated the containers with:
```
docker run -it --rm --link=docker_sfmdevapp_1:api --volumes-from=docker_sfmdata_1 --volume=/home/kerchner/projects/sfm-twitter-harvester:/opt/sfm-twitter-harvester --volume=/home/kerchner/projects/sfm-flickr-harvester:/opt/sfm-flickr-harvester --volume=/home/kerchner/projects/sfm-utils:/opt/sfm-utils gwul/sfm-processing:dev
```

And result is:
```
root@d31c7d08dc43:/sfm-data# twitter_rest_warc_iter.py
bash: twitter_rest_warc_iter.py: command not found

root@d31c7d08dc43:/sfm-data# cd /opt/sfm-utils
root@d31c7d08dc43:/opt/sfm-utils# git status
On branch sfm_227-iteration_env
Your branch is up-to-date with 'origin/sfm_227-iteration_env'.
```

**Comment by kerchner** [comment]
@justinlittman Thanks, confirmed that https://github.com/gwu-libraries/sfm-twitter-harvester/commit/407c3f9e5171509ea44491ed2bc3e47ac9c859dc fixes the "processing locally" setup issue for me as well.

**Comment by justinlittman** [comment]
@kerchner What is the full output from your `docker run`? It should do a `python setup.py install` which should install `twitter_rest_warc_iter.py` as a command.

**Comment by kerchner** [comment]
@justinlittman I rebuilt my processing container, re-ran docker run, seems to work now.  Not sure what the issue was.  I think we're good to merge now. :+1:

**Pull request merged**
