### PR TITLE
T172 export ui

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
Here's a docker-compose that can be used with minor modifications to test:
```
sfmdb:
    image: gwul/sfm-ui-db:master
#    build: db
    environment:
        - POSTGRES_PASSWORD=gherD42#dl5
        - TZ=EST
sfmapp:
#    image: gwul/sfm-ui:dev
#    build: app-dev
#    build: app-dev-runserver
    image: gwul/sfm-ui:dev-runserver
#    build: app-prod
    ports:
        - "8081:80"
    links:
        - sfmdb:db
        - sfmrabbit:mq
    environment:
        - SFM_DEBUG=True
        - SFM_APSCHEDULER_LOG=DEBUG
#        - SFM_DJANGO_LOG=DEBUG
        - SFM_UI_LOG=DEBUG
        - SFM_FIVE_MINUTE_SCHEDULE=True
        - TZ=EST
    volumes:
        - "..:/opt/sfm-ui"
        - "../../sfm-utils:/opt/sfm-utils"
    volumes_from:
        - sfmdata:ro
sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbatMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
        - TZ=EST
sfmdata:
    image: ubuntu:14.04
    command: /bin/true
    volumes:
#        - ~/tmp/sfmtest:/sfm-data
         - /sfm-data
    environment:
        - TZ=EST
sfmflickrharvester:
    image: gwul/sfm-flickr-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "../../sfm-flickr-harvester:/opt/sfm-flickr-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
        - "../../warcprox:/opt/warcprox"
#    restart: always
    environment:
        - DEBUG=True
        - TZ=EST
    volumes_from:
        - sfmdata
sfmflickrexporter:
    image: gwul/sfm-flickr-exporter:dev
    links:
        - sfmrabbit:mq
        - sfmapp:api
    volumes:
        - "../../sfm-flickr-harvester:/opt/sfm-flickr-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
        - "../../warcprox:/opt/warcprox"
#    restart: always
    environment:
        - DEBUG=True
        - TZ=EST
    volumes_from:
        - sfmdata

#sfmheritrix:
##    build: heritrix
#    image:  gwul/sfm-heritrix:master
#    ports:
#        - "8443:8443"
#    environment:
#        - HERITRIX_USER=sfm_user
#        - HERITRIX_PASSWORD=password
#    volumes_from:
#        - sfmdata
#sfmwebharvester:
##    build: dev
#    image: gwul/sfm-web-harvester:dev
#    links:
#        - sfmrabbit:mq
#        - sfmheritrix:heritrix
#    volumes:
#        - "../../sfm-web-harvester:/opt/sfm-web-harvester"
#        - "../../sfm-utils:/opt/sfm-utils"
#    environment:
#        - DEBUG=True
#        - HERITRIX_CONTACT_URL=http://library.gwu.edu
#    volumes_from:
#        - sfmheritrix
##    restart: always
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "../../sfm-twitter-harvester:/opt/sfm-twitter-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
        - "../../warcprox:/opt/warcprox"
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
sfmtwitterrestexporter:
#    image: gwul/sfm-twitter-rest-exporter:dev
    build: ../../sfm-twitter-harvester/docker/dev/rest-exporter
    links:
        - sfmrabbit:mq
        - sfmapp:api
    volumes:
        - "../../sfm-twitter-harvester:/opt/sfm-twitter-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
        - "../../warcprox:/opt/warcprox"
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
```

**Comment by justinlittman** [comment]
@lwrubel - I've rebased.  Don't forget to pull the latest master from sfm-utils and sfm-flickr-harvester before bringing up containers.

**Comment by lwrubel** [comment]
It looks like the seeds in the export are supposed to show up in export_detail.html but I'm not seeing them.

**Comment by justinlittman** [comment]
Based on discussion with @lwrubel, need to add indication to export details page when seed set (i.e., all seeds) is being exported.

**Comment by justinlittman** [comment]
@lwrubel I've kicked the additional work into a separate ticket (#219) because it depends on #181.

**Comment by lwrubel** [comment]
Noting that issue with dates causing flick-rexporter error is documented and fixed in #216.

@justinlittman: What happens if I request an export before a harvest occurs? I tried this on gwu_lisner as a seed, only 6 photos. I expected it to show "completed failure” or wait until there is content and then do the export. Actual behavior: the status stays as “requested”, even when the harvest eventually happens and there is content.

**Comment by lwrubel** [comment]
Was able to successfully get "completed failure" export status on a seedset with no harvests. Previous problem may have had to do with having other problem exports earlier in line.

**Comment by lwrubel** [comment]
Noting that dehydrate export option depends on https://github.com/gwu-libraries/sfm-utils/pull/9

**Pull request merged**
