### PR TITLE
Fixes #661 - Broken Tables and Change Logs fixed

### LINKED ISSUE #661: Long track filter busts tables
Keep tables from breaking when there's a long string for the twitter filter seed field. 

screen shot 2017-01-31 at 4 47 20 pm

### PR DESCRIPTION
**Pull request by rithvikmundra**

### CODE REVIEW

**Comment by lwrubel** [comment]
As discussed, apply this style to seed_detail.html as well. Since this is in a bunch of places at this point, create a style in main.css and add that to the templates instead of inline styles.

**Comment by lwrubel** [comment]
@rithvikmundra I think there is also something going on with the bootstrap rows, with a row nested within another, and thus making you put fixed widths on the table columns. If you can check the rows, you may be able to get rid of that part of the html.

**Comment by rithvikmundra** [comment]
@lwrubel I made the necessary modification. Please verify the same.

**Comment by rithvikmundra** [comment]
Closing this pull request so that I can delete this branch and can start from scratch.

**Pull request closed without merging**
