### PR TITLE
Fixes #688 - Shortens field length for login and sign up page

### LINKED ISSUE #688: Use diagram to help with Twitter collection screens
Create a graphic showing the elements of a tweet that affect collection set-up. Point out user image, user banner image, media, web page. Place diagram on twitter collection create pages.

### PR DESCRIPTION
**Pull request by adityadharne**

### CODE REVIEW

**Comment by adityadharne** [comment]
Fixes #668 not 688.

**Comment by adityadharne** [comment]
- This adds space on the right of the screen
- Should we add some text/rules on the now empty space? (links to readthedocs or http://go.gwu.edu/sfm)

**Comment by lwrubel** [comment]
@adityadharne this looks good to me. Considering your thought about open space: what about using the space on the right to put a blurb about SFM. Something like "​Social Feed Manager empowers researchers and archivists to create collections of social media data from Twitter, Tumblr, Flickr, and Sina Weibo. ​Read more about Social Feed Manager." (Read more links to docs.)

That could also go on the main page before someone selects log in / sign up, in a similar arrangement.

**Comment by lwrubel** [comment]
@adityadharne Noting that tests are not passing in Travis. Looks good overall. 

Some minor tweaks: in the info paragraph, change "Read more about Social Manager here." to a linked sentence: "Read more about Social Feed Manager." (I know we've talked about different approaches, but I'd like to avoid "click here" links.)

While you're there, bold the words "Social Feed Manager" at the very beginning.

**Pull request merged**
