### PR TITLE
Fixes #1003. Creates customizable institution footer; GW footer optio…

### LINKED ISSUE #1003: GW footer
w/accessibility links etc.

### PR DESCRIPTION
**Pull request by kerchner**
…n; improvements to upper footer.

### CODE REVIEW

**Comment by kerchner** [comment]
To test:
- View site with code as-is.  Inspect footer.
- Modify the following variables in the sfm-docker `.env` file and note the changes to the "SFM version 2.2.0 is a service of ___ " footer line (values here are notional):
   - if SFM_INSTITUTION_NAME is not configured, the line just displays "SFM version 2.2.0"
   - if SFM_INSTITUTION_NAME is configured, the line also adds " is a service of GW Libraries".  If SFM_INSTITUTION_LINK is also configured, GW Libraries is a link.
- In the sfm_ui code, modify:
   - `sfm/ui/templates/footer.html` - Follow the instructions in the comment to enable the GW footer.
   - `sfm/ui/static/css/footer.css` - Follow the instructions in the comment to enable the GW footer CSS

**Comment by kerchner** [comment]
I just realized that customizing the footer in this way would require the "ui" docker container to have a developement-type configuration, pointing to sfm-ui files outside of the container.  I will have to think about this.  We can discuss.

**Comment by kerchner** [comment]
NEW test instructions:
To test:

### Upper footer changes

Modify the `SFM_INSTITUTION_NAME` and `SFM_INSTITUTION_LINK` variables in the sfm-docker .env file and note the changes to the "SFM version 2.2.0 is a service of ___ " footer line (values here are notional):
- if SFM_INSTITUTION_NAME is not configured (i.e. value is commented out or blank), the line just displays "SFM version 2.2.0"
- if SFM_INSTITUTION_NAME is configured, the line also adds " is a service of GW Libraries". If SFM_INSTITUTION_LINK is also configured, GW Libraries is a link.

### Lower footer changes

- Deploy https://github.com/gwu-libraries/sfm-docker/pull/27
- Update .env file to include new `SFM_ENABLE_GW_FOOTER` variable as per `example.env`, using the example/default value of `False`
- View site. Inspect footer. Confirm that the lower, GW-specific footer does not appear.
- in `.env`, set `SFM_ENABLE_GW_FOOTER` to `True`.  Remove ui container.
- Restart the application and observe that the GW footer appears.

If the PR reviewer concurs that this is a satisfactory approach to allowing customization of the footer, I will freeze the code and proceed with a subsequent commit that will add associated documentation to this branch/PR.

**Comment by lwrubel** [comment]
@kerchner I agree this approach is satisfactory. The GW footer looks very nice there and SFM looks fine without it as well. I tested using the steps above and all of it worked as expected. I see you created a gw directory in the various static directories, and that seems like a good way to separate those GW-specific files. 

With all of the focus on the footer, there are two small UI tweaks I'm wondering if we could put into this branch for consistency and tidiness: 

1. With the accessibility color changes, we updated the color of links to a darker blue that's also a GW blue. As a result, the footer-blue class should have color: #297107 like other links now. 
2. I'm seeing the underline of two upper footer links extend a space beyond the links. This isn't because of any change in this code, just evident with underlined links now. Acknowledging it's not part of implementing new footers, but since it's in the footer code you're updating, would you close the <a> tags on the same line as the User Guide and Documentation link text?  

Go ahead with the remaining documentation/ instructions portions of this issue.

**Comment by kerchner** [comment]
@lwrubel Changes in your comment above have been made (including documentation).  Ready for review.

**Comment by lwrubel** [comment]
Looks good to go!

**Pull request merged**
