### PR TITLE
refs #54. Adds history support to Credentials, Collections, SeedSets,…

### PR DESCRIPTION
**Pull request by justinlittman**
… and Seeds. This includes tracking history and displaying on detail page. Also, hooks harvest into history to record the Credentials, SeedSets, and Seeds used to request the harvest.

### CODE REVIEW

**Comment by justinlittman** [comment]
To test:
1. Create and change credentials, collections, seed sets, and seeds in the UI or Admin. Note the addition of a note field.
2. Go to the details page for credentials, collections, seed sets, and seeds. Note the addition of a list of changes to the object.  This list should reflect the changes made to each field of the object, the time of the change, the user that made the change, and the note (if provided).
3. Go to Admin. Note the addition of historical credentials, collections, seed sets, and seeds.

**Comment by kerchner** [comment]
Making no changes to an object, but saving, results in a new Historical object.  Is the correct behavior when there are no diffs to any fields in `diff_fields` ?

**Comment by justinlittman** [comment]
It is.  `diff_fields` is something I added and is only used to determine which fields to display diffs for.

**Comment by kerchner** [comment]
What would it take for us to avoid creating a Historical object if this was a no-change save?  @lwrubel suggests perhaps using validation (on the ui side) to not save if we determine that the object hasn't changed.

**Comment by justinlittman** [comment]
@kerchner Made the suggested change so that only creates historical record when diff field is changed.

**Comment by kerchner** [comment]
@justinlittman The code certainly looks right, but no-change saves are still creating new Historical objects.

Also while you're in there, would you consider a slightly more descriptive value for `HISTORY_NOTE_LABEL` than `"Note"`?  Granted, there is `HISTORY_NOTE_HELP`, but perhaps something like `"Change Note"` would be even clearer.

**Comment by kerchner** [comment]
@justinlittman Disregard.   `history_save` is working correctly.

**Comment by kerchner** [comment]
Please proceed with squash (and update `HISTORY_NOTE_LABEL` if you agree)

**Comment by justinlittman** [comment]
@kerchner - Good to go.

**Pull request merged**
