### PR TITLE
T368 emails

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
Suggestions for testing:
* Make sure you have email correctly configured in your .env file.
* Make sure some of the users have email addresses (preferably to accounts that you can check).
* Setup some harvests and wait. Emails are sent over night, unless you chance SFM_USER_HARVEST_EMAILS_HOUR and SFM_USER_HARVEST_EMAILS_MINUTE.

**Comment by justinlittman** [comment]
@kerchner This is ready for assigning.

**Comment by justinlittman** [comment]
@lwrubel I removed the extraneous print statement.

Happy to use other wording for email message. Just let me know.

**Comment by lwrubel** [comment]
I'm not sure what other wording to use, so let's leave this and see what feedback we get.

**Pull request merged**
